describe('Backoffice', () => {
  describe('Navbar', () => {
    it('should change active tab', () => {
      cy.visit("/")
      cy.contains('Back office').click()
      cy.get('.navbar-container > :nth-child(1) > .h-20 > :nth-child(1)')
      .find('hr[class~="bg-transparent border-t-0"]')
      .should('not.exist')
      cy.contains('Reports').click()
      cy.get('.navbar-container > :nth-child(1) > .h-20 > :nth-child(3)')
      .find('hr[class~="bg-transparent border-t-0"]')
      .should('not.exist')
      cy.contains('Help').click()
      cy.get('.navbar-container > :nth-child(1) > .h-20 > :nth-child(4)')
      .find('hr[class~="bg-transparent border-t-0"]')
      .should('not.exist')
    })
  })
  describe('Create discount modal', () => {
    it('should open modal', () => {
      cy.visit("/")
      cy.contains('CREATE NEW DISCOUNT').click()
      cy.get('app-new-discount-modal').should('exist')
    })
    it('should close modal', () => {
      cy.visit("/")
      cy.contains('CREATE NEW DISCOUNT').click()
      cy.get('app-new-discount-modal').should('exist')
      cy.get('button[name="close-button"]').click()
      cy.get('app-new-discount-modal').should('not.exist')
    })
  })
  describe('Discount filtering', () => {
    it('should filter discounts by discount name', () => {
      cy.visit("/")
      cy.get('input[name="freeText"]').type('Bake sale')
      cy.contains('SEARCH').click()
      cy.get('tr[name="discount-result"]').should('have.length', 1)
    })
    it('should filter discounts by category', () => {
      cy.visit("/")
      cy.contains('Applies to').click()
      cy.contains('Event').click()
      cy.contains('SEARCH').click()
      cy.get('tr[name="discount-result"]').should('have.length', 2)
    })
    it('should clear all filters', () => {
      cy.visit("/")
      cy.get('input[name="freeText"]').type('Bake sale')
      cy.contains('Applies to').click()
      cy.contains('Event').click()
      cy.contains('SEARCH').click()
      cy.get('tr[name="discount-result"]').should('have.length', 1)
      cy.get('button[name="clear-filters"]').click()
      cy.get('tr[name="discount-result"]').should('have.length', 2)
    })
  })
  describe('Discount tab filtering', () => {
    it('should filter discounts based on active table tab', () => {
      cy.visit("/")
      cy.get('tr[name="discount-result"]').should('have.length', 2)
      cy.contains('Upcoming').click()
      cy.get('tr[name="discount-result"]').should('have.length', 6)
      cy.contains('Archived').click()
      cy.get('tr[name="discount-result"]').should('have.length', 10)
      cy.contains('Currently active').click()
      cy.get('tr[name="discount-result"]').should('have.length', 2)
    })
  })
  describe('Pagination', () => {
    it('should go to next page', () => {
      cy.visit("/")
      cy.contains('Archived').click()
      cy.get('tr[name="discount-result"]').should('have.length', 10)
      cy.get('button[name="next-page"]').click()
      cy.get('div[class~="pagination"]')
      .contains("1")
      .find('hr')
      .should('not.exist')
      cy.get('div[class~="pagination"]')
      .contains("2")
      .find('hr')
      .should('exist')
    })
  })
})